services:
  # Production service (default)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "6969:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/planner.db
    restart: unless-stopped
