services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Mount SQLite database directory
      - ./data:/app/data
      # For development hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/app/data/planner.db
    command: sh -c "npx prisma migrate dev && npm run dev"
    restart: unless-stopped

  # Production service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/planner.db
    restart: unless-stopped
    profiles:
      - production
